    <header role="banner">
        <h1>Actualités / Informations</h1>
        <div id="news">
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu felis turpis. Sed nulla quam, facilisis et risus aliquam, accumsan hendrerit mauris. Pellentesque id bibendum diam, ut volutpat justo. Quisque suscipit dolor nisl, id ultrices urna varius nec. Sed consectetur ut dui ac dignissim. Nam ac est id lectus posuere varius. Praesent fringilla ullamcorper nunc, non viverra orci dignissim vel. Quisque imperdiet eu augue sed lacinia. Pellentesque quis rhoncus ante. In hac habitasse platea dictumst. Nulla suscipit sed mi vestibulum cursus. Nullam laoreet consectetur justo lobortis maximus. Nulla ultricies semper blandit.</p>
            <p class="one-news">second</p><p class="one-news">third</p></div>
    </header>